// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2hrtHF4miLzlgK64N0TcgkyJn4AsbCBk',
    appId: '1:221245640408:web:77b41bde47b07db0ad51ad',
    messagingSenderId: '221245640408',
    projectId: 'sewamitra-f60bb',
    authDomain: 'sewamitra-f60bb.firebaseapp.com',
    storageBucket: 'sewamitra-f60bb.firebasestorage.app',
    measurementId: 'G-V75RXKE564',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1_PxHfPeI-WLxCCjTQPEA2b07krlLQgg',
    appId: '1:221245640408:android:44593c7066b3c827ad51ad',
    messagingSenderId: '221245640408',
    projectId: 'sewamitra-f60bb',
    storageBucket: 'sewamitra-f60bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAclL535PKeBTOBvxrIkH_58HNJmCY75BU',
    appId: '1:221245640408:ios:ab41e9787c785679ad51ad',
    messagingSenderId: '221245640408',
    projectId: 'sewamitra-f60bb',
    storageBucket: 'sewamitra-f60bb.firebasestorage.app',
    androidClientId: '221245640408-r653iujgq1827ucv5tu15onvdcduldj4.apps.googleusercontent.com',
    iosClientId: '221245640408-q42b61ceiu80a3kr6vgabooc1qm1ng76.apps.googleusercontent.com',
    iosBundleId: 'com.example.sewamitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAclL535PKeBTOBvxrIkH_58HNJmCY75BU',
    appId: '1:221245640408:ios:ab41e9787c785679ad51ad',
    messagingSenderId: '221245640408',
    projectId: 'sewamitra-f60bb',
    storageBucket: 'sewamitra-f60bb.firebasestorage.app',
    androidClientId: '221245640408-r653iujgq1827ucv5tu15onvdcduldj4.apps.googleusercontent.com',
    iosClientId: '221245640408-q42b61ceiu80a3kr6vgabooc1qm1ng76.apps.googleusercontent.com',
    iosBundleId: 'com.example.sewamitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2hrtHF4miLzlgK64N0TcgkyJn4AsbCBk',
    appId: '1:221245640408:web:f09016cd16616238ad51ad',
    messagingSenderId: '221245640408',
    projectId: 'sewamitra-f60bb',
    authDomain: 'sewamitra-f60bb.firebaseapp.com',
    storageBucket: 'sewamitra-f60bb.firebasestorage.app',
    measurementId: 'G-WEG8GTB67R',
  );

}